version: '3'

services:

  postgres:
    container_name: postgres
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}

  web:
    container_name: web
    build: 
      context: web
    ports:
      - "3000:3000"
    environment:
      - PORT=${SERVER_PORT}
      - DECIMAL_DIGITS=${DECIMAL_DIGITS}
      - SECRET_KEY=${SECRET_KEY}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
    depends_on:
      - postgres

